sonata_user:
    security_acl:             false
    table:
        user_group:           fos_user_user_group

    impersonating:
        route:                sonata_admin_dashboard
        parameters:           { path: / }

    google_authenticator:
        enabled:              true
        server:               %sonata_user.google_authenticator.server%

    manager_type:             orm

    profile:
        form:
            type:                 sonata_user_profile
            handler:              sonata.user.profile.form.handler.default
            name:                 sonata_user_profile_form
            validation_groups:
                - Profile
                - Default